# Generated by Django 5.1 on 2025-05-26 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_associations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
