# Generated by Django 5.1 on 2025-05-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teaminvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_home', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='users.team')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('team', 'date')},
            },
        ),
    ]
