# Generated by Django 5.1 on 2025-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scheduleproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdate',
            name='allow_doubleheader',
            field=models.BooleanField(default=False),
        ),
    ]
