# Generated by Django 5.1 on 2025-06-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teamdate_allow_doubleheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSchedulingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6U', '6U'), ('7U', '7U'), ('8U', '8U'), ('10U', '10U'), ('12U', '12U'), ('14U', '14U'), ('16U', '16U'), ('18U', '18U'), ('Adult', 'Adult')], max_length=5)),
                ('tier', models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA'), ('B', 'B'), ('BB', 'BB'), ('C', 'C')], max_length=3)),
                ('availability_deadline', models.DateTimeField()),
                ('auto_schedule_enabled', models.BooleanField(default=True)),
                ('last_schedule_attempt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Deadline/Conditions'), ('triggered', 'Scheduling Triggered'), ('conflicts', 'Has Unresolved Conflicts'), ('completed', 'Schedule Complete'), ('manual_hold', 'Manual Hold')], default='waiting', max_length=20)),
                ('schedule_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_states', to='users.association')),
                ('unmatched_teams', models.ManyToManyField(blank=True, related_name='league_conflicts', to='users.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('age_group', 'tier', 'association')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_reminder', 'Deadline Reminder'), ('insufficient_availability', 'Insufficient Availability'), ('schedule_conflict', 'Schedule Conflict'), ('schedule_complete', 'Schedule Complete')], max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('league_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.leagueschedulingstate')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_notifications', to='users.team')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
