# Generated by Django 5.1 on 2025-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_leagueschedulingstate_schedulingnotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagueschedulingstate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='association',
        ),
        migrations.AddField(
            model_name='leagueschedulingstate',
            name='season',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='leagueschedulingstate',
            unique_together={('age_group', 'tier', 'season', 'association')},
        ),
    ]
