# Generated by Django 5.1 on 2025-06-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_team_association_add_season_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueschedulingstate',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of scheduled Celery task', max_length=100, null=True),
        ),
    ]
