# Generated by Django 5.1 on 2025-06-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_leagueschedulingstate_celery_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueschedulingstate',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='leagueschedulingstate',
            name='task_scheduled',
            field=models.BooleanField(default=False, help_text='Whether a deadline task is scheduled'),
        ),
    ]
