# Generated by Django 5.1 on 2025-06-23 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_replace_celery_with_task_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('6U', '6U'), ('7U', '7U'), ('8U', '8U'), ('10U', '10U'), ('12U', '12U'), ('14U', '14U'), ('16U', '16U'), ('18U', '18U'), ('Adult', 'Adult')], max_length=5)),
                ('tier', models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA'), ('B', 'B'), ('BB', 'BB'), ('C', 'C')], max_length=3)),
                ('season', models.CharField(default='2024-2025', max_length=9)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active schedule')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_schedules', to='users.association')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('age_group', 'tier', 'season', 'association', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('series', 'Series'), ('single', 'Single Game'), ('doubleheader', 'Doubleheader')], default='series', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled'), ('conflict', 'Conflict')], default='scheduled', max_length=15)),
                ('dates', models.JSONField(help_text='List of match dates in YYYY-MM-DD format')),
                ('conflict_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='users.team')),
                ('generated_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.generatedschedule')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='users.team')),
            ],
            options={
                'ordering': ['dates'],
            },
        ),
    ]
