# Generated by Django 5.1 on 2025-06-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_system_settings'),
    ]

    operations = [
        # Rename the model from LeagueSchedulingState to DivisionSchedulingState
        migrations.RenameModel(
            old_name='LeagueSchedulingState',
            new_name='DivisionSchedulingState',
        ),
    ]
