# Generated by Django 5.1 on 2025-06-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20250625_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulingnotification',
            old_name='league_state',
            new_name='division_state',
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, help_text="Club's primary location (e.g., city, rink, or address).", max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='divisionschedulingstate',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_states', to='users.association'),
        ),
        migrations.AlterField(
            model_name='divisionschedulingstate',
            name='unmatched_teams',
            field=models.ManyToManyField(blank=True, related_name='division_conflicts', to='users.team'),
        ),
    ]
