# Generated by Django 5.1 on 2025-07-16 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20250627_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=10)),
                ('tier', models.CharField(max_length=5)),
                ('season', models.CharField(max_length=20)),
                ('log_type', models.CharField(choices=[('team_readiness', 'Team Readiness Check'), ('schedule_generation', 'Schedule Generation'), ('user_login', 'User Login'), ('team_added', 'Team Added'), ('team_deleted', 'Team Deleted'), ('team_modified', 'Team Modified'), ('availability_updated', 'Team Availability Updated'), ('deadline_set', 'Deadline Set'), ('system_info', 'System Information')], max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.association')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['age_group', 'tier', 'season', 'association'], name='users_divis_age_gro_a9f906_idx'), models.Index(fields=['timestamp'], name='users_divis_timesta_ed6109_idx'), models.Index(fields=['log_type'], name='users_divis_log_typ_ee042c_idx')],
            },
        ),
    ]
