# Generated by Django 5.1 on 2025-07-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_divisionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionlog',
            name='log_type',
            field=models.CharField(choices=[('team_readiness', 'Team Readiness Check'), ('schedule_generation', 'Schedule Generation'), ('user_login', 'User Login'), ('team_added', 'Team Added'), ('team_deleted', 'Team Deleted'), ('team_modified', 'Team Modified'), ('availability_updated', 'Team Availability Updated'), ('deadline_set', 'Deadline Set'), ('system_info', 'System Information'), ('email_notification', 'Email Notification Sent')], max_length=30),
        ),
    ]
