# Generated by Django 5.1 on 2025-07-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_unique_team_name_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Try different ways to find and remove the unique constraint
                "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_team_name') THEN ALTER TABLE users_team DROP CONSTRAINT unique_team_name; END IF; END $$;",
                "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_team_name_key') THEN ALTER TABLE users_team DROP CONSTRAINT users_team_name_key; END IF; END $$;",
                "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_team_name_unique') THEN ALTER TABLE users_team DROP CONSTRAINT users_team_name_unique; END IF; END $$;",
            ],
            reverse_sql=[
                # Don't add any constraints back
            ]
        ),
    ]
